### ISSUE TITLE
Stop creation of log and tmp folder

### ISSUE THREAD

**Issue by bhavya0901** [highcharts/node-export-server#491] opened 2024-03-18 05:21 UTC
#### Actual behaviour
highcharts-export-server create log and tmp folder during chart image download process but kubernetes does not allow to create a folder like this.

#### Expected behaviour
chart image will download without creation log and tmp folder.

I think after adding `options.logging.level = 0` log folder not created, same as log folder which code require to stop creation of tmp folder

**Comment by bhavya0901** [comment] 2024-03-20 07:03
```
const exportSettings = {
          export: {
            type: "png",
            options: report_config.data,
          },
        };
        
        const options = exporter.setOptions(exportSettings);
        options.logging.level = 0 // to remove log folder when image download
        await exporter.initPool(options);
        
        exporter.startExport(exportSettings, async function (res, err) {
          if (err) {
            log.info("Error in exporting chart : " + err); // error comes from here when code deployed on live server
            return resp.status(500).send({ msg: err.message });
          }
          log.info("buffer data getting")
          const binaryData = Buffer.from(res.data, "base64");
          exporter.killPool();
```

I've write above code to get chart image and it's perfectly working fine in my local but when I'm getting **In pool.postWork: [pool] Error when acquiring available entry: Error** when code deployed on live server

I think tmp folder doesn't created on live server and due to this reason I'm getting this error may be Kubernetes does not allow to create tmp folder on live server

Do you have any solution to resolve this issue ?

**Comment by bhavya0901** [comment] 2024-03-21 05:09
> Thanks for the question!
> 
> In highcharts-export-server v4.0.0, we'll introduce the `cachePath` option which will allow you to change the caching directory (which has been a problem on AWS Lambda) so the cache directory will no longer have to be inside this.
> 
> As you've correctly pointed out, when `options.logging.level = 0`, the `log` folder should not be created. We could consider adding an additional option which would prevent the server from creating the log directory.
> 
> When it comes to the `tmp` folder, it is necessary for the puppeteer to run correctly. Could you please elaborate on the problem with this? Isn't there a way to change the write permissions within Kubernetes (I'm not sure, but this might be related: https://discuss.kubernetes.io/t/write-permissions-on-volume-mount-with-security-context-fsgroup-option/16524)?

I've mentioned my issue in detail , please check

**Comment by jszuminski** [comment] 2024-03-28 11:13
Closing as it's a duplicate of this issue: https://github.com/highcharts/node-export-server/issues/501

**Closed by jszuminski** 2024-03-28 11:13 UTC
Labels: duplicate, environment issue
