### ISSUE TITLE
How can generate map

### ISSUE THREAD

**Issue by andreyfomin** [highcharts/node-export-server#183] opened 2018-12-17 16:51 UTC

**Comment by andreyfomin** [comment] 2018-12-17 16:52
The question is how can I generate map graph on server site, you don't have any example :(

**Comment by KacperMadej** [comment] 2018-12-17 17:59
Hi, thanks for contacting us! You've posted to our issue tracker.

The solution is presented in this issue thread: https://github.com/highcharts/node-export-server/issues/128

In case of a need for technical support, please see www.highcharts.com/support.
Closing as not a bug.

**Closed by KacperMadej** 2018-12-17 17:59 UTC
