### ISSUE TITLE
Inquiry Regarding Enhancement Request

### ISSUE THREAD

**Issue by bhavya0901** [highcharts/node-export-server#518] opened 2024-04-24 09:09 UTC
Hi @jszuminski ,

I hope you're doing well! I wanted to check in to see if there have been any updates on the enhancement request I made recently. https://github.com/highcharts/node-export-server/issues/501

Looking forward to hearing from you.

**Comment by jszuminski** [comment] 2024-05-16 10:23
Closing as a duplicate of: https://github.com/highcharts/node-export-server/issues/501

**Closed by jszuminski** 2024-05-16 10:23 UTC
