### ISSUE TITLE
SVG Marker

### ISSUE THREAD

**Issue by timfaase** [highcharts/node-export-server#384] opened 2023-02-09 13:28 UTC
Using the latest build version https://github.com/highcharts/node-export-server/tree/enhancement/puppeteer. We ran into an issue with a chart that has an svg marker.

See json below. The chart is not rendered, no error is logged whatsoever. (Log level 4; verbose).

Can we get this svg marker to work?
And can we get the error handling improved with some relevant feedback/logging?

JSON:

```{
    "xAxis": {
        "categories": [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec"
        ]
    },
    "series": [
        {
            "data": [1,3,2,4],
            "type": "line",
            "marker": {
            "enabled": true,
            "height": 18,
            "width": 18,
            "radius": 25,
            "symbol": "url(data:image/svg+xml;base64,PHN2ZyBhcmlhLWhpZGRlbj0idHJ1ZSIgZm9jdXNhYmxlPSJmYWxzZSIgZGF0YS1wcmVmaXg9ImZhcyIgZGF0YS1pY29uPSJ1c2VyIiBjbGFzcz0ic3ZnLWlubGluZS0tZmEgZmEtdXNlciIgcm9sZT0iaW1nIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBmaWxsPSIjMjhhMDg1IiBkPSJNMjI0IDI1NmM3MC43IDAgMTI4LTU3LjMgMTI4LTEyOFMyOTQuNyAwIDIyNCAwUzk2IDU3LjMgOTYgMTI4czU3LjMgMTI4IDEyOCAxMjh6bS00NS43IDQ4Qzc5LjggMzA0IDAgMzgzLjggMCA0ODIuM0MwIDQ5OC43IDEzLjMgNTEyIDI5LjcgNTEySDQxOC4zYzE2LjQgMCAyOS43LTEzLjMgMjkuNy0yOS43QzQ0OCAzODMuOCAzNjguMiAzMDQgMjY5LjcgMzA0SDE3OC4zeiI+PC9wYXRoPjwvc3ZnPg==)",
            "states": {
              "hover": {
                "enabled": false
              }
          }
      }
        },
        {
            "data": [5,3,4,2],
            "type":"line"
        }
    ]
}
```

**Comment by timfaase** [comment] 2023-04-11 14:06
Hi Paul,

Thanks for your response! Just checked it; works for png indeed, but still does nog work for svg...

**Comment by PaulDalek** [comment] 2023-04-11 14:25
@timfaase

I've used the same command but instead use the svg extension and still, the symbol is visible. Could you provide me with the command you use? For the reference, here is the result SVG:

`<svg version="1.1" class="highcharts-root" style="font-family: &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, Arial, Helvetica, sans-serif; font-size: 12px;" xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400" aria-hidden="false" aria-label="Interactive chart"><desc aria-hidden="true">Created with Highcharts 10.3.3</desc><defs aria-hidden="true"><clipPath id="highcharts-f3w450f-13-"><rect x="0" y="0" width="530" height="272" fill="none"></rect></clipPath><clipPath id="highcharts-f3w450f-18-"><rect x="0" y="0" width="530" height="272" fill="none"></rect></clipPath><clipPath id="highcharts-f3w450f-23-"><rect x="60" y="53" width="530" height="272" fill="none"></rect></clipPath></defs><rect fill="#ffffff" class="highcharts-background" x="0" y="0" width="600" height="400" rx="0" ry="0" aria-hidden="true"></rect><rect fill="none" class="highcharts-plot-background" x="60" y="53" width="530" height="272" aria-hidden="true"></rect><g class="highcharts-pane-group" data-z-index="0" aria-hidden="true"></g><g class="highcharts-grid highcharts-xaxis-grid" data-z-index="1" aria-hidden="true"><path fill="none" stroke="#e6e6e6" stroke-width="0" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 192.5 53 L 192.5 325" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="0" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 324.5 53 L 324.5 325" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="0" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 457.5 53 L 457.5 325" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="0" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 589.5 53 L 589.5 325" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="0" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 59.5 53 L 59.5 325" opacity="1"></path></g><g class="highcharts-grid highcharts-yaxis-grid" data-z-index="1" aria-hidden="true"><path fill="none" stroke="#e6e6e6" stroke-width="1" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 60 325.5 L 590 325.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 60 280.5 L 590 280.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 60 234.5 L 590 234.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 60 189.5 L 590 189.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 60 144.5 L 590 144.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 60 98.5 L 590 98.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" stroke-dasharray="none" data-z-index="1" class="highcharts-grid-line" d="M 60 52.5 L 590 52.5" opacity="1"></path></g><rect fill="none" class="highcharts-plot-border" data-z-index="1" stroke="#cccccc" stroke-width="0" x="60" y="53" width="530" height="272" aria-hidden="true"></rect><g class="highcharts-axis highcharts-xaxis" data-z-index="2" aria-hidden="true"><path fill="none" class="highcharts-axis-line" stroke="#ccd6eb" stroke-width="1" data-z-index="7" d="M 60 325.5 L 590 325.5"></path></g><g class="highcharts-axis highcharts-yaxis" data-z-index="2" aria-hidden="true"><text x="26" data-z-index="7" text-anchor="middle" transform="translate(0,0) rotate(270 26 189)" class="highcharts-axis-title" style="color: rgb(102, 102, 102); fill: rgb(102, 102, 102);" y="189">Values</text><path fill="none" class="highcharts-axis-line" stroke="#ccd6eb" stroke-width="0" data-z-index="7" d="M 60 53 L 60 325"></path></g><g class="highcharts-series-group" data-z-index="3" aria-hidden="false"><g class="highcharts-series highcharts-series-0 highcharts-line-series highcharts-color-0" data-z-index="0.1" opacity="1" transform="translate(60,53) scale(1 1)" clip-path="url(#highcharts-f3w450f-18-)" aria-hidden="true"><path fill="none" d="M 66.25 226.666666666667 L 198.75 136 L 331.25 181.333333333333 L 463.75 90.66666666667001" class="highcharts-graph" data-z-index="1" stroke="#7cb5ec" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"></path><path fill="none" d="M 66.25 226.666666666667 L 198.75 136 L 331.25 181.333333333333 L 463.75 90.66666666667001" data-z-index="2" class="highcharts-tracker-line" stroke-linecap="round" stroke-linejoin="round" stroke="rgba(192,192,192,0.0001)" stroke-width="22"></path></g><g class="highcharts-markers highcharts-series-0 highcharts-line-series highcharts-color-0 highcharts-tracker" data-z-index="0.1" opacity="1" transform="translate(60,53) scale(1 1)" clip-path="none" aria-hidden="false" role="region" tabindex="-1" aria-label="Series 1, line 1 of 2 with 4 data points." style="outline: none;"><image preserveAspectRatio="none" xlink:href="data:image/svg+xml;base64,PHN2ZyBhcmlhLWhpZGRlbj0idHJ1ZSIgZm9jdXNhYmxlPSJmYWxzZSIgZGF0YS1wcmVmaXg9ImZhcyIgZGF0YS1pY29uPSJ1c2VyIiBjbGFzcz0ic3ZnLWlubGluZS0tZmEgZmEtdXNlciIgcm9sZT0iaW1nIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBmaWxsPSIjMjhhMDg1IiBkPSJNMjI0IDI1NmM3MC43IDAgMTI4LTU3LjMgMTI4LTEyOFMyOTQuNyAwIDIyNCAwUzk2IDU3LjMgOTYgMTI4czU3LjMgMTI4IDEyOCAxMjh6bS00NS43IDQ4Qzc5LjggMzA0IDAgMzgzLjggMCA0ODIuM0MwIDQ5OC43IDEzLjMgNTEyIDI5LjcgNTEySDQxOC4zYzE2LjQgMCAyOS43LTEzLjMgMjkuNy0yOS43QzQ0OCAzODMuOCAzNjguMiAzMDQgMjY5LjcgMzA0SDE3OC4zeiI+PC9wYXRoPjwvc3ZnPg==" x="66" y="226.666666666667" width="18" transform="translate(-9,-9)" height="18" stroke="#ffffff" stroke-width="0" fill="#7cb5ec" opacity="1" class="highcharts-point highcharts-color-0" tabindex="-1" role="img" aria-label="Jan, 1. Series 1." style="outline: none;"></image><image preserveAspectRatio="none" xlink:href="data:image/svg+xml;base64,PHN2ZyBhcmlhLWhpZGRlbj0idHJ1ZSIgZm9jdXNhYmxlPSJmYWxzZSIgZGF0YS1wcmVmaXg9ImZhcyIgZGF0YS1pY29uPSJ1c2VyIiBjbGFzcz0ic3ZnLWlubGluZS0tZmEgZmEtdXNlciIgcm9sZT0iaW1nIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBmaWxsPSIjMjhhMDg1IiBkPSJNMjI0IDI1NmM3MC43IDAgMTI4LTU3LjMgMTI4LTEyOFMyOTQuNyAwIDIyNCAwUzk2IDU3LjMgOTYgMTI4czU3LjMgMTI4IDEyOCAxMjh6bS00NS43IDQ4Qzc5LjggMzA0IDAgMzgzLjggMCA0ODIuM0MwIDQ5OC43IDEzLjMgNTEyIDI5LjcgNTEySDQxOC4zYzE2LjQgMCAyOS43LTEzLjMgMjkuNy0yOS43QzQ0OCAzODMuOCAzNjguMiAzMDQgMjY5LjcgMzA0SDE3OC4zeiI+PC9wYXRoPjwvc3ZnPg==" x="198" y="136" width="18" transform="translate(-9,-9)" height="18" stroke="#ffffff" stroke-width="0" fill="#7cb5ec" opacity="1" class="highcharts-point highcharts-color-0" tabindex="-1" role="img" aria-label="Feb, 3. Series 1." style="outline: none;"></image><image preserveAspectRatio="none" xlink:href="data:image/svg+xml;base64,PHN2ZyBhcmlhLWhpZGRlbj0idHJ1ZSIgZm9jdXNhYmxlPSJmYWxzZSIgZGF0YS1wcmVmaXg9ImZhcyIgZGF0YS1pY29uPSJ1c2VyIiBjbGFzcz0ic3ZnLWlubGluZS0tZmEgZmEtdXNlciIgcm9sZT0iaW1nIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBmaWxsPSIjMjhhMDg1IiBkPSJNMjI0IDI1NmM3MC43IDAgMTI4LTU3LjMgMTI4LTEyOFMyOTQuNyAwIDIyNCAwUzk2IDU3LjMgOTYgMTI4czU3LjMgMTI4IDEyOCAxMjh6bS00NS43IDQ4Qzc5LjggMzA0IDAgMzgzLjggMCA0ODIuM0MwIDQ5OC43IDEzLjMgNTEyIDI5LjcgNTEySDQxOC4zYzE2LjQgMCAyOS43LTEzLjMgMjkuNy0yOS43QzQ0OCAzODMuOCAzNjguMiAzMDQgMjY5LjcgMzA0SDE3OC4zeiI+PC9wYXRoPjwvc3ZnPg==" x="331" y="181.333333333333" width="18" transform="translate(-9,-9)" height="18" stroke="#ffffff" stroke-width="0" fill="#7cb5ec" opacity="1" class="highcharts-point highcharts-color-0" tabindex="-1" role="img" aria-label="Mar, 2. Series 1." style="outline: none;"></image><image preserveAspectRatio="none" xlink:href="data:image/svg+xml;base64,PHN2ZyBhcmlhLWhpZGRlbj0idHJ1ZSIgZm9jdXNhYmxlPSJmYWxzZSIgZGF0YS1wcmVmaXg9ImZhcyIgZGF0YS1pY29uPSJ1c2VyIiBjbGFzcz0ic3ZnLWlubGluZS0tZmEgZmEtdXNlciIgcm9sZT0iaW1nIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBmaWxsPSIjMjhhMDg1IiBkPSJNMjI0IDI1NmM3MC43IDAgMTI4LTU3LjMgMTI4LTEyOFMyOTQuNyAwIDIyNCAwUzk2IDU3LjMgOTYgMTI4czU3LjMgMTI4IDEyOCAxMjh6bS00NS43IDQ4Qzc5LjggMzA0IDAgMzgzLjggMCA0ODIuM0MwIDQ5OC43IDEzLjMgNTEyIDI5LjcgNTEySDQxOC4zYzE2LjQgMCAyOS43LTEzLjMgMjkuNy0yOS43QzQ0OCAzODMuOCAzNjguMiAzMDQgMjY5LjcgMzA0SDE3OC4zeiI+PC9wYXRoPjwvc3ZnPg==" x="463" y="90.66666666667001" width="18" transform="translate(-9,-9)" height="18" stroke="#ffffff" stroke-width="0" fill="#7cb5ec" opacity="1" class="highcharts-point highcharts-color-0" tabindex="-1" role="img" aria-label="Apr, 4. Series 1." style="outline: none;"></image></g><g class="highcharts-series highcharts-series-1 highcharts-line-series highcharts-color-1" data-z-index="0.1" opacity="1" transform="translate(60,53) scale(1 1)" clip-path="url(#highcharts-f3w450f-18-)" aria-hidden="true"><path fill="none" d="M 66.25 45.33333333332999 L 198.75 136 L 331.25 90.66666666667001 L 463.75 181.333333333333" class="highcharts-graph" data-z-index="1" stroke="#434348" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"></path><path fill="none" d="M 66.25 45.33333333332999 L 198.75 136 L 331.25 90.66666666667001 L 463.75 181.333333333333" data-z-index="2" class="highcharts-tracker-line" stroke-linecap="round" stroke-linejoin="round" stroke="rgba(192,192,192,0.0001)" stroke-width="22"></path></g><g class="highcharts-markers highcharts-series-1 highcharts-line-series highcharts-color-1 highcharts-tracker" data-z-index="0.1" opacity="1" transform="translate(60,53) scale(1 1)" clip-path="none" aria-hidden="false" role="region" tabindex="-1" aria-label="Series 2, line 2 of 2 with 4 data points." style="outline: none;"><path fill="#434348" d="M 66 49 A 4 4 0 1 1 66.00399999933333 48.99999800000017 Z" stroke="#ffffff" stroke-width="0" opacity="1" class="highcharts-point highcharts-color-1" tabindex="-1" role="img" aria-label="Jan, 5. Series 2." style="outline: none;"></path><path fill="#434348" d="M 198 140 A 4 4 0 1 1 198.00399999933333 139.99999800000018 Z" stroke="#ffffff" stroke-width="0" opacity="1" class="highcharts-point highcharts-color-1" tabindex="-1" role="img" aria-label="Feb, 3. Series 2." style="outline: none;"></path><path fill="#434348" d="M 331 95 A 4 4 0 1 1 331.00399999933336 94.99999800000016 Z" stroke="#ffffff" stroke-width="0" opacity="1" class="highcharts-point highcharts-color-1" tabindex="-1" role="img" aria-label="Mar, 4. Series 2." style="outline: none;"></path><path fill="#434348" d="M 463 185 A 4 4 0 1 1 463.00399999933336 184.99999800000018 Z" stroke="#ffffff" stroke-width="0" opacity="1" class="highcharts-point highcharts-color-1" tabindex="-1" role="img" aria-label="Apr, 2. Series 2." style="outline: none;"></path></g></g><text x="300" text-anchor="middle" class="highcharts-title" data-z-index="4" style="color: rgb(51, 51, 51); font-size: 18px; fill: rgb(51, 51, 51);" y="24" aria-hidden="true">Chart title</text><text x="300" text-anchor="middle" class="highcharts-subtitle" data-z-index="4" style="color: rgb(102, 102, 102); fill: rgb(102, 102, 102);" y="52" aria-hidden="true"></text><text x="10" text-anchor="start" class="highcharts-caption" data-z-index="4" style="color: rgb(102, 102, 102); fill: rgb(102, 102, 102);" y="397" aria-hidden="true"></text><g class="highcharts-legend highcharts-no-tooltip" data-z-index="7" transform="translate(214,359)" aria-hidden="true"><rect fill="none" class="highcharts-legend-box" rx="0" ry="0" stroke="#999999" stroke-width="0" x="0" y="0" width="171" height="26"></rect><g data-z-index="1"><g><g class="highcharts-legend-item highcharts-line-series highcharts-color-0 highcharts-series-0" data-z-index="1" transform="translate(8,3)"><path fill="none" class="highcharts-graph" stroke-width="2" stroke-linecap="round" d="M 1 11 L 15 11" stroke="#7cb5ec"></path><image preserveAspectRatio="none" xlink:href="data:image/svg+xml;base64,PHN2ZyBhcmlhLWhpZGRlbj0idHJ1ZSIgZm9jdXNhYmxlPSJmYWxzZSIgZGF0YS1wcmVmaXg9ImZhcyIgZGF0YS1pY29uPSJ1c2VyIiBjbGFzcz0ic3ZnLWlubGluZS0tZmEgZmEtdXNlciIgcm9sZT0iaW1nIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48cGF0aCBmaWxsPSIjMjhhMDg1IiBkPSJNMjI0IDI1NmM3MC43IDAgMTI4LTU3LjMgMTI4LTEyOFMyOTQuNyAwIDIyNCAwUzk2IDU3LjMgOTYgMTI4czU3LjMgMTI4IDEyOCAxMjh6bS00NS43IDQ4Qzc5LjggMzA0IDAgMzgzLjggMCA0ODIuM0MwIDQ5OC43IDEzLjMgNTEyIDI5LjcgNTEySDQxOC4zYzE2LjQgMCAyOS43LTEzLjMgMjkuNy0yOS43QzQ0OCAzODMuOCAzNjguMiAzMDQgMjY5LjcgMzA0SDE3OC4zeiI+PC9wYXRoPjwvc3ZnPg==" x="8" y="11" width="12" transform="translate(-6,-6)" height="12" class="highcharts-point" stroke="#ffffff" stroke-width="0" fill="#7cb5ec" opacity="1"></image><text x="21" text-anchor="start" data-z-index="2" y="15" style="color: rgb(51, 51, 51); cursor: pointer; font-size: 12px; font-weight: bold; fill: rgb(51, 51, 51);">Series 1</text></g><g class="highcharts-legend-item highcharts-line-series highcharts-color-1 highcharts-series-1" data-z-index="1" transform="translate(95.71875,3)"><path fill="none" class="highcharts-graph" stroke-width="2" stroke-linecap="round" d="M 1 11 L 15 11" stroke="#434348"></path><path fill="#434348" d="M 8 15 A 4 4 0 1 1 8.003999999333336 14.999998000000167 Z" class="highcharts-point" stroke="#ffffff" stroke-width="0" opacity="1"></path><text x="21" y="15" text-anchor="start" data-z-index="2" style="color: rgb(51, 51, 51); cursor: pointer; font-size: 12px; font-weight: bold; fill: rgb(51, 51, 51);">Series 2</text></g></g></g></g><g class="highcharts-axis-labels highcharts-xaxis-labels" data-z-index="7" aria-hidden="true"><text x="126.25" text-anchor="middle" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="344" opacity="1">Jan</text><text x="258.75" text-anchor="middle" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="344" opacity="1">Feb</text><text x="391.25" text-anchor="middle" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="344" opacity="1">Mar</text><text x="523.75" text-anchor="middle" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="344" opacity="1">Apr</text></g><g class="highcharts-axis-labels highcharts-yaxis-labels" data-z-index="7" aria-hidden="true"><text x="45" text-anchor="end" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="329" opacity="1">0</text><text x="45" text-anchor="end" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="284" opacity="1">1</text><text x="45" text-anchor="end" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="238" opacity="1">2</text><text x="45" text-anchor="end" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="193" opacity="1">3</text><text x="45" text-anchor="end" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="148" opacity="1">4</text><text x="45" text-anchor="end" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="102" opacity="1">5</text><text x="45" text-anchor="end" transform="translate(0,0)" style="color: rgb(102, 102, 102); cursor: default; font-size: 11px; fill: rgb(102, 102, 102);" y="57" opacity="1">6</text></g><text x="590" class="highcharts-credits" text-anchor="end" data-z-index="8" y="395" style="cursor: pointer; color: rgb(153, 153, 153); font-size: 9px; fill: rgb(153, 153, 153);" aria-label="Chart credits: Highcharts.com" aria-hidden="false">Highcharts.com</text><g class="highcharts-control-points" data-z-index="99" clip-path="url(#highcharts-f3w450f-23-)" aria-hidden="true"></g></svg>`

**Comment by PaulDalek** [comment] 2023-04-11 16:00
@timfaase

Yes, you are right. In a nutshell the result which is then embedded into HTML is a base64 representation of a chart. It works correctly most of the time but this is a special situation when the generated SVG also contains base64 elements for each symbol, therefore transforming the SVG with base64 strings into a base64 generates an incorrect result. I'll mark it as a bug and try to fix it shortly. I guess the solution here would simply be to place the whole SVG into html but we need to analyze it further. Thanks for reporting it.

**Comment by PaulDalek** [comment] 2023-11-20 17:07
Closing, as the UI export is already fixed in the newest version. Checked this particular case and export is performed as intended.

**Closed by PaulDalek** 2023-11-20 17:07 UTC
Labels: bug, puppeteer
