### ISSUE TITLE
0x04 error when performing chart generation: please check your input data

### ISSUE THREAD

**Issue by JHAServiceTrace** [highcharts/node-export-server#287] opened 2021-06-22 06:37 UTC
Hello,

unfortunately, your support at https://support.highcharts.com/ could not help me with the following question and recommended to open an issue here.

We use your Highcharts Export Server as an HTTP server. In higher load the export server occasionally responds with **400 (Bad Request)**. The response body contains the error message **0x04 error when performing chart generation: please check your input data**. The error occurs in lower load as well, but at a longer runtime. If this error appears once, it seams to appear more often over time. Thus we have to restart the HTTP server.

In the chapter "[Worker Count & Work Limit](https://github.com/highcharts/node-export-server#worker-count--work-limit)" of your documentation you recommend using the stress test "tests/http/stress-test.js". With the aid of this stress test, I am able to reproduce the 0x04 error. We made tests on a Windows Server 2019 Standard installation and on Ubuntu 20.04. Both show the 0x04 error. Our tests start the export server with the following CLI arguments:

`highcharts-export-server --enableServer 1 --port 7801 --logLevel 4 --logDest . --workers 10`

I changed the interval from 10 ms to 1000 ms. After a while the following error occur multiple times in the log file:

...
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [notice] restarting worker. working = false
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [verbose] starting export
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [verbose] phantom - found available worker
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [verbose] phantom 110 - starting work
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [verbose] phantom 112 - spawning worker
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [verbose] got incoming HTTP request 51bc2e0761b14a28965ce031dfe4ed3c
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [verbose] attempting to export from raw input
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [verbose] phantom - received work, finding available worker
Tue Jun 15 2021 07:21:43 GMT+0100 (GMT+01:00) [error] work 95244a6725ba42109291f538d7b73f8a could not be completed, sending: 0x04 error when performing chart generation: please check your input data
...

If I do not specify a worker count, 4 workers are started per default. With this setting, the error occurs later (after a longer runtime). If I specify 30 workers, the error occurs earlier (after a shorter runtime).

What can we do that this error does not occur? What component is responsible for this error. As far as I can see in the source code, the error occurs while restarting the PhantomJS process.

Thanks in advance.

Regards

   Jochen

**Comment by jakubSzuminski** [comment] 2023-08-23 13:51
Closing as it's a duplicate of this issue: https://github.com/highcharts/node-export-server/issues/268

**Closed by jakubSzuminski** 2023-08-23 13:51 UTC
