### ISSUE TITLE
PDF Export, image wrong scale

### ISSUE THREAD

**Issue by vitalvv** [highcharts/node-export-server#88] opened 2017-10-06 14:57 UTC
Exporting a chart to PDF produces a valid PDF file bu the chart image itself is not the right scale, its too small. Link to screenshot: https://i.imgur.com/A81ExSr.png

The only option I specify for exporting in highchart configuration is 
allowHTML: true
url: "url"

The POST contains:
'filename' => string 'chart' (length=5)
  'type' => string 'application/pdf' (length=15)
  'width' => string '0' (length=1)
  'scale' => string '2' (length=1)
  'svg' => string '...'

**Comment by PaulDalek** [comment] 2018-04-06 15:25
+1

**Comment by stefangu** [comment] 2018-09-07 15:46
Hi.
I have probably the same issue. When exporting PDF, the chart does not fill out the image.
More details here -> https://forum.highcharts.com/posting.php?mode=reply&f=9&t=40995&sid=85ebfffc0500778fd8ed64ad9f5d32a0

I solved this by exporting png and add it to my pdf file. I was not able to export pdf image with a correct chart size inside, isn't this a bug ?

Regards,
Stefán

**Comment by KacperMadej** [comment] 2018-09-10 08:29
Hi @stefangu 

This demo seems to be working fine - https://www.highcharts.com/demo/line-basic
and a demo with empty chart work fine for me too - https://jsfiddle.net/BlackLabel/ekgz2hq1/

Please provide a live demo for the problem or provide more info.

Tested with Chrome - exported through Chrome and viewed the exported PDF in Chrome

**Comment by stefangu** [comment] 2018-09-10 13:31
Hi Kacper.
Your demo is using client side export, I am calling my own highchart node export server which I setup on my local windows laptop. That‘s way it is difficult for me to produce live demo for you. My export server version is v2.0.15 and my Node version is v8.11.3. OS is windows 10 (I also tried this on windows server 2008)

This is an example, I call my highchart export server from command line using .json script file. The .json script looks like this:

{
    "series": [{
    "data": [
      [2018, 10],
      [2019, 11],
      [2020, 12],
	  [2021, 13],
	  [2022, 13]
    ]
  }]
}

And I execute these commands:
1) "highcharts-export-server --infile testchart.json --outfile chart.png"
2) "highcharts-export-server --infile testchart.json --outfile --type pdf chart.pdf"

The out put for this are two files, chart.pdf and chart.png. See 

![chart](https://user-images.githubusercontent.com/43071940/45300199-3a248e80-b4fd-11e8-9ee0-f236ecbffc5d.png)

[chart.pdf](https://github.com/highcharts/node-export-server/files/2366772/chart.pdf)

Can you see the difference, the pdf chart is not filling out the image. I hope this helps. Other wise I can just use png instead of pdf to solve this.

Regards,
Stefán

**Comment by potmat** [comment] 2019-02-11 15:27
+1

**Comment by ahmad-rzk** [comment] 2019-07-24 12:03
Any updates?
I am having the same issue

**Comment by sabt** [comment] 2020-12-09 09:47
Hi,

 I have set up my own highcharts-export-server (v2.0.28).

I use the CLI form of rendering and exporting maps, i.e. without HTML frontend. The width and sourceWidth (+ height and sourceHeight) are correctly set for the map. Scale has been set to 1. The desired size is 238 px x 321 px, but the exported PDF has a size of 317px x 427px. Scale value (2,3...) have no effect on my exported PDF. How do I resolve this ? I have now tested with export server v2.0.24 too, with same results.

Additionally - I tested a random online pdf export with the same result - https://jsfiddle.net/sibeeshvenu/pwLo7112/   

"options": {
    "chart": {      
      borderWidth: 0,
      margin: [0, 0, 0, 0],
      width: 238,
      height: 321,
      spacing: [0, 0, 0, 0],
      }
    },
    "exporting": {
      sourceWidth: 238,
      sourceHeight: 321,      
      scale: 1
    }

Thank you.

**Comment by sabt** [comment] 2020-12-10 09:36
Do we have an update on this PDF export size problem ? I was directed here by highcharts support so that the developers could look into it.

Thank you.

**Comment by PaulDalek** [comment] 2020-12-10 16:32
Hi @sabt

Thank you for contacting us and reporting this issue. Could you please provide us with the full options of the exported map along with the used CLI command? Thanks.

**Comment by sabt** [comment] 2020-12-11 08:29
Hi,
 I have attached the settings file. Sorry about the miscommunication,  I don't directly use the CLI command, instead use node module - call with a cURL POST to a render function on the server. (curl --request POST "http://localhost:3000/render" ). The CLI options are translated into settings.js that is used in the export call as

``highchartsExportServer.export(settings, function (err, res) {
      //The export result is now in res.
      //If the output is not PDF or SVG, it will be base64 encoded (res.data).
      //If the output is a PDF or SVG, it will contain a filename (res.filename)
      if (err) {
        console.log(err);
      }

      //Kill the pool when we're done with it, and exit the application
      highchartsExportServer.killPool();
      //process.exit(1);      
    });
  });

thank you.

[settings-support.zip](https://github.com/highcharts/node-export-server/files/5677912/settings-support.zip)

**Comment by PaulDalek** [comment] 2020-12-11 16:31
@sabt

I tested your JSFiddle demo and ran your options in a simple node module (also sent POST using Curl) and it seems that exported PDF has the right height/width. Could you generate the chart and provide me with a PDF file?

**Comment by sabt** [comment] 2020-12-14 13:29
Hi,

 here is the PDF I exported. It is 3.31 in X  4.46 in ( about 318 pixel X 428 pixel ).  FYI, the jsfiddle I mentioned is not mine, I just used it as a random test.

thanks.

[myPDF.pdf](https://github.com/highcharts/node-export-server/files/5689002/myPDF.pdf)

**Comment by PaulDalek** [comment] 2020-12-14 15:30
@sabt

Ok, thanks for the PDF but could you also provide me with the full options that you use to generate the map? Thanks.

**Comment by sabt** [comment] 2020-12-15 08:22
I am not sure I understand your question. Do you want the geojson ? I have attached the settings file above which is all the options I use for (rendering and) exporting. I have once again attached the options (settings) file with geojson and csv processing code, which I thought was irrelevant to chart options. Please check. Thank you.

[settings-support.zip](https://github.com/highcharts/node-export-server/files/5694279/settings-support.zip)

**Comment by PaulDalek** [comment] 2020-12-16 16:56
@sabt

I have created a simple node module based on your options and the data from the https://jsfiddle.net/BlackLabel/0q8j93uv/ and it seems everything works as expected. Setting `sourceWidth`, `sourceHeight` and `scale` exports the file and the initial size is correct. Also, the behavior that you encounter isn’t the same as the one reported initially (it concerns white spaces on PDFs when exported on Windows OS), so please instead of continuing here, create a new GH issue or support ticket through one of the available [support channels](https://www.highcharts.com/blog/support/).

[module_test.zip](https://github.com/highcharts/node-export-server/files/5704184/module_test.zip)

**Comment by sabt** [comment] 2020-12-17 07:53
Thanks, I see that the jsfiddle you created exports with scale (e.g. doubles at scale:2) but I still see the PDF is slightly bigger than expected (can be seen in File - Properties). We will hopefully resize and use the maps, if there is no explanation for this behaviour. We can close this here then.

We don't have any issues with the white spaces, that has been dealt with, It happens only on windows server, as support confirmed last year. We use Debian.

**Comment by PaulDalek** [comment] 2022-04-07 16:44
This chart's measurements problem occurs on Windows machines when using the PhantomJS version of the export server. It seems that the problem is no more when it comes to Puppeteer based export server (tested on Windows 11, using the `enhancement/puppeteer` branch).

**Closed as completed by PaulDalek** 2022-04-07 16:44 UTC
Labels: pending reply
