### ISSUE TITLE
Highcharts cache folder

### ISSUE THREAD

**Issue by istvanherbak** [highcharts/node-export-server#574] opened 2024-08-23 12:08 UTC
#### Expected behaviour
The cache folder for Highcharts in config should work with absolute file path.

#### Actual behaviour
Currently the cache folder is always joined to the base folder of the highcharts-export-server thus always forcing the cache folder to be located under it.

**Comment by DanielRuf** [comment] 2024-08-24 13:09
Duplicate of https://github.com/highcharts/node-export-server/issues/562.

**Comment by jszuminski** [comment] 2024-08-26 06:19
Closing as it's a duplicate.

**Closed by jszuminski** 2024-08-26 06:19 UTC
