### ISSUE TITLE
The "Server Test" in README doesn't work

### ISSUE THREAD

**Issue by aik099** [highcharts/node-export-server#163] opened 2018-08-10 09:41 UTC
#### Expected behaviour

The `highcharts-export-server --enableServer 1` command shown in README do something.

#### Actual behaviour
Got an exception:

```
    __  ___       __         __               __                      
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______                
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/                
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )                 
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/                  
        ____//___/                  __     _____                          
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /    
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/     
              /_/                                                         
               
                                                                  v2.0.15
uncaughtException: TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:380:11)
    at exports.spawn (child_process.js:487:38)
    at Object.exports.exec (/usr/local/lib/node_modules/highcharts-export-server/node_modules/phantomjs-prebuilt/lib/phantomjs.js:72:10)
    at spawnWorker (/usr/local/lib/node_modules/highcharts-export-server/lib/phantompool.js:127:32)
    at Object.init [as initPool] (/usr/local/lib/node_modules/highcharts-export-server/lib/phantompool.js:330:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/highcharts-export-server/bin/cli.js:193:10)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

**Comment by aik099** [comment] 2018-08-10 10:25
Related to #132.

**Comment by KacperMadej** [comment] 2018-08-14 09:32
@aik099 Is this only related? Looks like a duplicate for me.

**Comment by aik099** [comment] 2018-08-14 09:50
At time of posting I wasn't aware, that same error happens regardless of arguments being passed. Yes, this is a duplicate.

**Comment by KacperMadej** [comment] 2018-08-14 10:36
No problem, just wanted to be sure.
Duplicate of #132

**Closed by KacperMadej** 2018-08-14 10:36 UTC
Labels: pending clarification
