### ISSUE TITLE
plotBackgroundImage doesn't work with node-export-server

### ISSUE THREAD

**Issue by raf18seb** [highcharts/node-export-server#186] opened 2019-02-15 13:37 UTC
Like in the title. Node export server is not able to process neither .jpg nor base64 images.

#### Reproduction steps
I use **highcharts-export-server --infile test.json**
In test.json file I have this config like this:

```
{

  chart: {
    type: 'bubble',
    plotBackgroundImage: 'https://www.highcharts.com/samples/graphics/skies.jpg'
  },

  xAxis: {
    min: 0,
    max: 1.3
  },

  yAxis: {
    min: 0,
    max: 70
  },

  series: [{
    color: 'yellow',
    name: 'Sun',
    data: [{
      x: 1,
      y: 55,
      z: 0
    }]
  }]

}
```

jsFiddle with above config: https://jsfiddle.net/BlackLabel/2tvcdqrs

highcharts-export-server v2.0.16
node v10.15.1

**Comment by hlorofos** [comment] 2019-04-01 16:27
Dear  highcharts representatives, any progress on this?

**Comment by TorsteinHonsi** [comment] 2019-04-08 12:36
@cvasseng , any comment? Async problems maybe?

**Comment by cvasseng** [comment] 2019-05-08 09:58
Did you pass it as written? If so, try formatting as JSON instead of JavaScript:

    {

      "chart": {
        "type": "bubble",
        "plotBackgroundImage": "https://www.highcharts.com/samples/graphics/skies.jpg"
      },

      "xAxis": {
        "min": 0,
        "max": 1.3
      },

      "yAxis": {
        "min": 0,
        "max": 70
      },

      "series": [{
        "color": "yellow",
        "name": "Sun",
        "data": [{
          "x": 1,
          "y": 55,
          "z": 0
        }]
      }]

    }

If that still doesn't work, please try the latest version `2.0.19` which seems to produce the correct result on my local test setup.

**Comment by jeremyjclarke** [comment] 2019-09-27 00:44
Reviving this topic.  This JSON doesn't produce a background image on the Export Server test page either: https://export.highcharts.com/

@highcharts - any ideas?

**Comment by brunaobh** [comment] 2019-10-07 18:07
I'm facing the same issue here - Node export server is not able to process neither .png nor base64 images.

Reproduction steps
I use highcharts-export-server --infile test.json
In test.json file I have this config like this:

```
{

  chart: {
    type: 'bubble',
    plotBackgroundImage: 'https://www.highcharts.com/samples/graphics/skies.jpg'
  },

  xAxis: {
    min: 0,
    max: 1.3
  },

  yAxis: {
    min: 0,
    max: 70
  },

  series: [{
    color: 'yellow',
    name: 'Sun',
    data: [{
      x: 1,
      y: 55,
      z: 0
    }]
  }]

}
```

highcharts-export-server v2.0.24
node v8.16.1

**Comment by softfrog** [comment] 2020-06-05 15:30
+1

any response @highcharts?

**Comment by pawelfus** [comment] 2020-06-08 16:12
Just debugged, it seems that the reason lies in.. Highcharts core. Exporting server expects `chart.events.load` to be called after all images are loaded. In fact, that applies to all `symbol`-like generated images (e.g. markers), but does not work with other images (e.g. `plotBackgroundImage`).

Workaround is to create a dummy series with marker that will load the image, snippet with explanation:
```js
{
  "chart": {
    "type": "bubble",
    "plotBackgroundImage": "https://www.highcharts.com/samples/graphics/skies.jpg"
  },

  "series": [{
    // Dummy series, that is rendered under the actual one
    "type": "scatter",
    // Hidden from legend
    "showInLegend": false,
    "marker": {
      // Visible, but hidden
      "radius": 0.0001,
      // Path to image we want to use
      "symbol": "url(https://www.highcharts.com/samples/graphics/skies.jpg)"
    },
    "data": [] // copy of one point in original series
  }, {
    "color": "yellow",
    "name": "Sun",
    "data": [{
      "x": 1,
      "y": 55,
      "z": 0
    }]
  }]
}
```

**Working example:**
```json
{
  "chart": {
    "type": "bubble",
    "plotBackgroundImage": "https://www.highcharts.com/samples/graphics/skies.jpg"
  },

  "xAxis": {
    "min": 0,
    "max": 1.3
  },

  "yAxis": {
    "min": 0,
    "max": 70
  },

  "series": [{
    "type": "scatter",
    "showInLegend": false,
    "marker": {
      "radius": 0.0001,
      "symbol": "url(https://www.highcharts.com/samples/graphics/skies.jpg)"
    },
    "data": [{
      "x": 1,
      "y": 55
    }]
  }, {
    "color": "yellow",
    "name": "Sun",
    "data": [{
      "x": 1,
      "y": 55,
      "z": 0
    }]
  }]
}
```

**Comment by softfrog** [comment] 2020-06-09 18:39
Aha! I'm using the background image for a polar chart, so just set the marker in the dummy series to show centered on the chart and plotted the actual series on top of that. Completely avoided using plotBackgroundImage (I'm exporting to pdf so don't need any live behaviour). Works like a charm.

Thanks @pawelfus !

**Comment by 100phel** [comment] 2020-06-19 17:17
I'm facing a similar issue. The SVGs are loaded like 2 times out of 10 when used in the markers:
```
"series": [
    {
      "type": "line",
      "lineWidth": 0,
      "data": [
        {
          "x": 1592586000000,
          "y": 86,
          "marker": {
            "symbol": "url(https://dots.dataontouchdev.com/images/weather/yr_weather_symbols/svg/01d.svg)",
            "width": 40,
            "height": 40
          }
        },
...
```

**Comment by pawelfus** [comment] 2020-06-22 09:05
Just to avoid answering in every ticket (#43 and #238), I will just answer here. Is that ok with you @100phel ? I believe, there's no point to copy my answer in every ticket.

Just tested my solution above - you are right, sometimes it fails. After some tests it seems ~30% of the exported charts didn't include images properly. I don't know the reason. This seems to be happening only when exporting chart from JSON options, SVG seems to be fine..

There's an alternative solution - add resources and force chart to wait for loading all images, like this:

```
highcharts-export-server --infile test.json --resources '{ "files": "test.js", "asyncLoading": true }'
```

And `test.js` file:
```js
function checkImages() {
    if (Array.prototype.filter.call(document.images, function(img) { return !img.complete }).length === 0) {
        highexp.done();
    } else {
        setTimeout(checkImages, 0);
    }
}

setTimeout(checkImages, 0);
```

With this workaround, it's no longer necessary to create a dummy series.

**Comment by 100phel** [comment] 2020-06-22 10:01
@pawelfus Thank you for your time testing this but your solution still doesn't work for me.
`checkImages` does get called - I've checked that by adding one line to your code:

```javascript
function checkImages() {
    if (Array.prototype.filter.call(document.images, function(img) { return !img.complete }).length === 0) {
        throw new Error('Images: ' + JSON.stringify(document.images))

        highexp.done();
    } else {
        setTimeout(checkImages, 0);
    }
}

setTimeout(checkImages, 0);
```

And the output is:

`phantom worker 1 unexpected data - Error: Images: {"length":0}`

So, it seems like document doesn't contain any images and that's why `highexp.done()` gets called right away. And I still don't get any symbols on the chart.

**Comment by 100phel** [comment] 2020-06-22 10:11
Here's my json file:
```json
{
  "title": "Observation Forecast - Luke Lightfoot",
  "xAxis": [
    {
      "type": "datetime"
    }
  ],
  "yAxis": [
    {
      "title": {
        "text": "Temperature"
      }
    }
  ],
  "series": [
    {
      "type": "line",
      "lineWidth": 0,
      "data": [
        {
          "x": 1592888400000,
          "y": 73,
          "marker": {
            "symbol": "url(https://dots.dataontouchdev.com/images/weather/yr_weather_symbols/svg/22n.svg)",
            "width": 50,
            "height": 50
          }
        }
      ],
      "showInLegend": false
    }
  ],
  "asyncRendering": true,
  "resources": {
    "files": "resources.js"
  }
}

```
And here's the video just in case: https://www.awesomescreenshot.com/video/251118?key=53fb64c0330b20760898eda540b68660

Also, here's the expected output - I got it from pasting the above options file in the web version of https://export.highcharts.com/

https://tinyurl.com/yacoccus

**Comment by pawelfus** [comment] 2020-06-22 10:41
Ah, my bad! `highexp.done()` should be called **before** creating the chart. My code above doesn't make sense.

I have tried something like this (pre-load images):
```js
function checkImages() {
    if (Array.prototype.filter.call(document.images, function(img) { return !img.complete }).length === 0) {
        highexp.done();
    } else {
        setTimeout(checkImages, 0);
    }
}

function loadImages() {
    var img = document.createElement('img');

    img.src = 'https://dots.dataontouchdev.com/images/weather/yr_weather_symbols/svg/22n.svg';
    img.style.position = 'absolute';
    img.style.top = '-50px';
    img.style.height = '40px';
    img.style.width = '40px';
    document.body.appendChild(img);
}

loadImages();
setTimeout(checkImages, 0);
```

Tested 10x with your config - works fine. Could you check it and let me know the results?

**Comment by 100phel** [comment] 2020-06-22 10:45
@pawelfus Your solution in the web version works, thank you! 
But when I try it in the terminal I get the following error:
```
phantom worker 1 unexpected data - TypeError: null is not an object (evaluating 'document.body.appendChild')
```

**Comment by pawelfus** [comment] 2020-06-22 12:49
Hmm.. try then `document.querySelector('body')` or `document.querySelectorAll('body')[0]`? Perhaps we have different PhantomJS versions, hard to say.

**Comment by 100phel** [comment] 2020-06-22 14:39
@pawelfus I think I get the error because `loadImages` is called before the `document.body` is created...

**Comment by pawelfus** [comment] 2020-06-23 08:42
That might be it, did you try putting the code into `DOMContentLoaded` event's callback?

**Comment by 100phel** [comment] 2020-06-23 09:52
@pawelfus it worked! Thank you very much! The final solution looks like this:
```javascript
function checkImages() {
    if (document.body === null || Array.prototype.filter.call(document.images, function(img) { return !img.complete }).length === 0) {
        highexp.done();
    } else {
        setTimeout(checkImages, 0);
    }
}

function loadImages() {
    var img = document.createElement('img');

    img.src = 'https://dots.dataontouchdev.com/images/weather/yr_weather_symbols/svg/22n.svg';
    img.style.position = 'absolute';
    img.style.top = '-50px';
    img.style.height = '40px';
    img.style.width = '40px';

    document.body.appendChild(img);
}

window.addEventListener('DOMContentLoaded', function(event) {
    loadImages();
});

setTimeout(checkImages, 0);
```

**Comment by robertoferreirajrr** [comment] 2021-01-25 19:15
Any official fix for this issue?

**Comment by 100phel** [comment] 2021-03-15 07:59
@pawelfus The solution above worked until 2 days ago. Now I'm getting error: callback, resources, and customCode have been disabled for this server

So, seems like we can't use the `resources` parameter anymore.

**Comment by pawelfus** [comment] 2021-03-15 09:46
@100phel 
See: https://github.com/highcharts/node-export-server#breaking-changes-in-v210

**Comment by 100phel** [comment] 2021-03-16 13:52
@pawelfus I use the Highcharts export server (https://export.highcharts.com), so I can't utilize the `--allowCodeExecution` option that they suggest. Anyway, the `resources` parameter was utilized in order to overcome the bug that the library has - not loading the images. Now that we can't use this option anymore, is there any other way?

**Comment by pawelfus** [comment] 2021-03-16 15:49
FYI @PaulDalek @cvasseng

**Comment by icjosh10** [comment] 2021-04-16 05:41
None of these worked for me. Using chart to display to Discord using Node but no background Image tutorial I've used works 😢

**Comment by PaulDalek** [comment] 2022-05-27 17:04
Sorry for the late reply. This was a big deal in the PhantomJS version of the export server. It required using the `asyncLoading` along with resources and triggering the `highexp.done()` in order to wait for images. In the new [Puppeteer version](https://github.com/highcharts/node-export-server/tree/enhancement/puppeteer) this is no longer required, as it waits for the images to load. All you need to do is to simply place the URL as a value of a specific option (in this case `plotBackgroundImage`) and that’s it. Here is the result:
![chart](https://user-images.githubusercontent.com/19933566/170748609-71355a39-e6fc-41fa-a44e-dd105b9ae0f9.png)

**Closed by PaulDalek** 2022-05-27 17:04 UTC
