### ISSUE TITLE
how to use it when i use nodejs

### ISSUE THREAD

**Issue by tlhe** [highcharts/node-export-server#110] opened 2018-01-23 06:52 UTC
run example,use nodejs
![image](https://user-images.githubusercontent.com/32058135/35261829-e6aa057e-004c-11e8-8ce0-3bb6ea5cc26a.png)

**Comment by cvasseng** [comment] 2018-01-23 09:28
If you are still unable to install it (as you have described in #109), that would be the reason why you get this image. The install script bundles the Highcharts libraries into the generation templates. If the libraries are not there, you get this image.

I'm closing this as it seems like a dupe of your other issue. If you feel that it's not (i.e you've since successfully ran `npm install` or `node build.js` without errors), please re-open.

**Closed by cvasseng** 2018-01-23 09:28 UTC
