### ISSUE TITLE
column chart export https://export.highcharts.com/ 500 error

### ISSUE THREAD

**Issue by seolllll** [highcharts/node-export-server#531] opened 2024-05-24 01:19 UTC
```
Highcharts.chart('container', {
		chart:{
			type: 'column',
			zooming: {
            	type: 'x'
        	},
	        panning: true,
	        panKey: 'shift'		
		},
		title:{
			text: 'test'
		},
		exporting:{
			enabled: true,
			filename: 'test',
			sourceWidth: 1920,
        	sourceHeight: 1080,
			menuItemDefinitions: {	      
	        downloadPNG: {
								onclick: function () {
                  this.exportChart({
                        type: 'image/png',
                      })
	                }
	            },
			},
			buttons: {
				contextButton: {
        	align: 'right',
					menuItems: [						
						'downloadPNG',
					]					
				}
			}
		},
		credits: {
	  		enabled: false
  		},
		xAxis:{
			title:{
				text: 'test',			
			},
			categories: [202404,202403,202402,202401,202312,202311,202310,202309,202308,202307,202306,202305,202304,202303,202302,202301,202212,202211,202210,202209,202208,202207,202206,202205,202204,202203,202202,202201,202112,202111,202110,202109,202108,202107,202106,202105,202104,202103,202102,202101,202012,202011,202010,202009,202008,202007,202006,202005,202004,202003,202002,202001,201912,201911,201910,201909,201908,201907,201906,201905,201904,201903,201902,201901,201812,201811,201810,201809,201808,201807,201806,201805,201804,201803,201802,201801,201712,201711,201710,201709,201708,201707,201706,201705,201704,201703,201702,201701,201612,201611,201610,201609,201608,201607,201606,201605,201604,201603,201602,201601,201512,201511,201510,201509,201508,201507,201506,201505,201504,201503,201502,201501,201412,201411,201410,201409,201408,201407,201406,201405,201404,201403,201402,201401,201312,201311,201310,201309,201308,201307,201306,201305,201304,201303,201302,201301,201212,201211,201210,201209,201208,201207,201206,201205,201204,201203,201202,201201,201112,201111,201110,201109,201108,201107,201106,201105,201104,201103,201102,201101,201012,201011,201010,201009,201008,201007,201006,201005,201004,201003,201002,201001,200912,200911,200910,200909,200908,200907,200906,200905,200904,200903,200902,200901,200812,200811,200810,200809,200808,200807,200806,200805,200804,200803,200802,200801,200712,200711,200710,200709,200708,200707,200706,200705,200704,200703,200702,200701,200612,200611,200610,200609,200608,200607,200606,200605,200604,200603,200602,200601],
			min: 0,
        	max: 15,
			scrollbar: {
				enabled: true
		    }		  
		},
		yAxis:{
			title:{
				text: 'test'
			}
		},
		legend: {
			layout: 'vertical',
	        align: 'right',
	        verticalAlign: 'middle'
		},
		plotOptions: {
		    series: {
		        dataLabels: {
		            enabled: true
		        }
		    }
		},
		series: [{"name":"검사건수","data":[42,36,39,60,65,95,35,29,39,60,48,71,69,66,52,36,49,21,36,41,26,70,20,38,67,69,38,43,50,50,40,50,44,56,52,52,59,57,48,74,48,66,17,2,0,1,0,1,1,1,31,72,52,57,62,50,38,64,52,73,62,41,38,60,63,55,73,47,57,52,67,81,76,73,61,65,47,53,26,42,47,36,43,52,53,71,45,52,41,51,38,52,47,37,50,49,56,66,58,53,129,116,61,51,39,87,56,87,86,77,86,73,83,80,111,74,72,78,62,55,67,77,88,85,94,121,121,89,78,99,74,131,97,118,121,90,55,65,88,89,43,67,61,92,115,121,111,101,86,117,88,86,98,105,110,78,115,95,41,92,202,100,88,94,53,98,56,66,78,83,48,68,65,93,55,117,113,100,106,10,18,44,17,27,109,69,62,71,46,63,27,37,36,25,20,12,14,65,79,12,11,21,18,29,38,31,36,61,165,137,72,235,132,78,50,201,144,207,73,116]},{"name":"검사결과_ADV","data":[1,0,1,0,2,1,1,2,5,8,1,3,1,0,1,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,1,1,0,0,0,1,0,2,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,2,0,1,0,1,0,3,6,2,5,4,0,4,0,3,1,1,1,2,4,1,1,0,0,1,0,0,0,0,0,0,0,0,2,3,0,0,1,3,1,3,4,8,11,1,1,0,2,0,0,1,1,0,1,1,0,1,0,2,0,0,2,2,1,1,1,3,10,10,24,14,22,7,20,6,8,4,8,9,9,8,5,2,4,2,7,7,2,4,4,6,4,8,2,2,1,3,6,7,14,3,5,12,14,17,24,9,31,9,7,8,5,2,7,1,1,2,6,10,9,12,0,2,3,1,1,3,2,1,3,7,1,1,2,3,1,1,1,2,3,1,0,0,1,0,0,1,1,1,1,0,0,0,0,1,0,0,2,0,2,1,0]},{"name":"검사결과_RSV","data":[1,3,6,3,0,0,0,0,4,1,4,3,3,6,2,2,1,0,5,1,0,0,0,0,1,3,7,7,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,9,2,2,1,0,1,0,0,0,0,1,3,0,5,4,2,0,0,0,0,2,1,6,0,2,0,1,2,3,0,0,0,0,0,1,5,1,1,2,1,1,0,0,1,0,0,0,0,1,22,1,0,0,0,0,0,0,0,0,1,5,12,11,2,0,0,1,0,0,0,1,1,1,4,11,15,5,0,2,0,0,1,5,4,5,7,11,13,2,3,2,0,0,1,2,5,2,10,17,13,1,1,0,0,0,1,0,0,0,6,5,1,4,0,1,0,1,3,1,1,2,1,1,1,0,0,2,2,0,0,0,2,3,17,12,4,0,0,0,0,3,0,0,1,4,2,2,6,0,0,0,0,1,0,1,2,2,8,7,4,0,0,0,0,0,1,0,0,4]},{"name":"검사결과_PIV","data":[4,1,0,0,0,0,0,0,1,1,2,8,7,3,1,0,2,0,2,1,0,0,0,0,0,0,0,0,1,0,3,5,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2,1,3,0,0,9,11,12,1,2,0,1,1,0,3,1,3,9,7,11,2,0,0,2,0,0,1,2,4,4,7,6,1,1,1,0,0,2,0,3,2,5,7,6,3,1,0,0,5,7,15,2,3,2,2,13,3,0,0,0,0,1,1,0,6,7,10,8,2,0,0,2,1,6,6,7,11,14,7,13,1,3,0,2,1,1,0,7,10,8,6,17,4,2,0,1,0,0,0,0,0,0,2,4,4,1,0,0,1,3,3,4,2,5,3,5,3,0,0,1,0,0,0,3,3,4,2,2,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,1,0,0,0,0,0,0]},{"name":"검사결과_hRV","data":[8,4,0,2,2,12,11,8,4,10,4,11,14,10,7,1,1,6,3,2,2,8,2,4,8,0,4,1,7,19,5,3,4,12,6,3,7,5,2,0,7,11,0,0,0,1,0,0,0,0,0,1,10,15,6,10,4,15,5,11,9,10,6,6,7,12,12,13,3,6,12,17,19,13,4,0,1,6,4,5,4,3,7,5,6,5,4,3,4,8,5,10,7,8,10,7,11,11,3,4,11,23,0,9,7,8,6,8,11,5,5,4,4,11,14,3,6,5,10,6,10,5,0,3,4,12,16,15,11,24,19,17,15,20,11,13,7,12,29,11,6,18,18,23,5,23,8,5,10,28,29,12,15,18,12,5,5,2,1,2,6,13,14,5,8,8,7,9,4,6,4,6,5,12,10,11,13,22,37,2,4,12,2,1,8,25,10,10,7,7,4,7,13,14,4,4,3,12,9,2,2,7,4,8,14,17,6,8,8,1,0,0,0,0,0,0,0,0,0,0]},{"name":"검사결과_hBoV","data":[1,0,0,0,0,0,0,1,2,0,0,2,1,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,1,2,2,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,2,1,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,2,0,0,2,0,0,1,0,1,2,1,0,0,0,0,0,0,1,2,3,1,3,0,0,0,1,0,0,0,2,3,10,13,3,0,1,0,0,0,0,0,0,3,4,5,0,2,2,1,0,0,0,3,0,4,6,5,0,0,0,0,0,0,0,0,1,3,8,4,1,0,0,1,0,0,0,1,6,1,5,0,1,0,0,0,0,0,0,0,2,3,1,0,0,2,1,0,0,0,0,0,0,0,0,1,1,2,0,2,1,0,0,0,0,0,0,0,0,0,0,0]},{"name":"검사결과_HCoV","data":[1,5,2,7,9,5,0,0,1,2,1,2,2,6,12,4,3,0,0,1,0,2,2,1,0,7,4,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4,2,2,0,1,0,0,0,0,0,0,2,1,4,3,6,2,0,1,0,0,1,3,4,2,1,1,1,2,1,1,0,3,0,5,3,1,3,2,4,3,3,3,1,0,2,2,2,2,12,2,2,1,0,0,0,0,0,0,0,2,7,9,2,1,0,0,2,3,1,0,4,5,8,12,0,0,1,0,1,0,3,2,9,6,3,4,0,0,0,0,0,0,0,1,7,1,1,3,0,3,0,0,1,8,0,6,0,0,4,0,3,1,1,2,1,0,2,0,3,5,2,1,1,0,2,1,4,0,1,2,0,0,0,0,0,0,0,0,0,2,1,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0]},{"name":"검사결과_IFV","data":[2,3,6,12,34,30,4,3,5,7,6,3,1,0,5,9,12,0,1,1,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,31,5,0,0,2,2,0,0,2,17,3,2,28,26,3,0,1,0,0,0,1,1,5,23,43,20,2,1,2,2,1,0,4,9,9,8,22,15,2,0,1,2,0,0,4,8,9,12,4,0,0,0,0,1,0,0,1,15,37,32,16,2,0,0,0,0,0,0,0,7,32,63,33,0,1,0,0,0,0,0,0,9,16,37,17,1,0,0,0,0,0,0,2,38,39,41,48,12,1,0,3,2,0,0,0,38,2,3,33,83,1,3,4,0,0,0,0,46,37,4,12,14,30,12,5,2,1,1,0,2,0,0,0,2,0,0,0,0,0,0,0,3,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},{"name":"검사결과_hMPV","data":[4,2,1,0,2,2,0,0,1,7,7,4,2,6,2,2,0,4,3,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,1,2,1,1,1,3,9,6,2,0,0,0,1,0,0,1,3,4,12,14,4,1,0,0,0,0,0,0,0,1,4,12,8,1,1,1,0,0,0,2,0,1,4,8,7,1,0,1,0,0,0,0,2,0,9,4,0,0,0,0,0,0,0,0,0,0,4,5,0,3,0,0,0,0,0,0,1,0,0,3,8,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},{"name":"검출건수","data":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},{"name":"검출율","data":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}]
	})
```
![240524_1](https://github.com/highcharts/node-export-server/assets/101303525/a9a04ef5-2e33-4649-aea1-cbb211ba2aa7)

I keep getting "POST https://export.highcharts.com/ 500 (Internal Server Error)" while trying to download the chart
I tested it in various ways and found that if the chart has a lot of values drawn, that error occurs
There was an error when I drew the chart with 220 pieces of data, but when I reduced it to 100, it was downloaded without any problems
I wanted to use jsFiddle, but the chart isn't drawing as I intended, so I'll replace it with capture
Please tell me how to solve this problem

![240524_3](https://github.com/highcharts/node-export-server/assets/101303525/3af8bf11-437a-416a-b9e4-9f735fd68286)

**Comment by jszuminski** [comment] 2024-06-04 06:44
@seolllll thanks for reporting!

Most likely it's a duplicate of this issue: https://github.com/highcharts/node-export-server/issues/523 which has already been solved and will be a part of the next release.

**Closed by jszuminski** 2024-06-04 06:44 UTC
Labels: bug, duplicate
