### ISSUE TITLE
uncaughtException: Error: write EPIPE

### ISSUE THREAD

**Issue by liguangsong** [highcharts/node-export-server#66] opened 2017-06-26 11:14 UTC
system : ubuntu 16 64
node : v6.9.4
npm: 3.10.10
npm install node-export-server

exporter.initPool({reaper: false, maxWorkers: 1});
it is ok ,on mac. but  cant use in ubuntu 
uncaughtException: { Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' 
}

**Comment by cvasseng** [comment] 2017-08-09 11:23
This should be fixed in the current version (2.0.0).

Please feel free to reopen this if the issue isn't gone.

**Closed by cvasseng** 2017-08-09 11:23 UTC
